# Deployment and Service in 1 file because they belong to each other
apiVersion: apps/v1
kind: Deployment # the Blueprint for Pods

metadata:
  name: webapp-deployment
  namespace: k8s-demo-app
  labels:
    app: webapp

spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template: # Configuration for Pod and has its own metadata and spec section
    metadata:
      namespace: k8s-demo-app
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password    
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url          
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  namespace: k8s-demo-app
spec:
  type: NodePort 
  selector: # select pods to forward the request to.
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 # same as container port
      nodePort: 30100
